spring.application.name={{appName}}

#Datasource
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:falae_db_v2}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:3memvhyka93v}

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=${TOKEN_SECRET_KEY:zT#xVnu_-EL5E188~'FPv,BNNxMMr!ii#8fN#@%$kZQANBD.fuR6@cNQwZe-VXUe;mT}o2g$y;-FBcB~s<.*m,$/}
jwt.expiration=86400000

#Logging
logging.level.com.example=DEBUG
logging.level.org.springframework.security=DEBUG

#flyway
spring.flyway.locations=classpath:db/migration/postgres
spring.flyway.enabled=true
